import networkx as nx

graph = {
    "blk": ["nzx"],
    "mzf": ["kcv", "mmx", "csz"],
    "grk": ["qmh", "xxm", "dxg"],
    "vrd": ["fqs", "jfv", "jtf", "zmc"],
    "ldq": ["nbc", "rqp", "skf", "zjx"],
    "qcx": ["pbk"],
    "jds": ["khc", "jxj", "bsx", "ssn"],
    "gjf": ["ggd", "hqg", "vjn", "khc", "xcg", "dxl", "dpj"],
    "qnm": ["ndh", "tsv", "blv", "ftc", "jkf"],
    "xzp": ["qvb"],
    "zjm": ["xqc", "dsp", "gdg", "chr"],
    "jpq": ["jpz"],
    "qrp": ["zsv"],
    "tlk": ["fqn", "hrp", "pzm", "xxs", "lvg"],
    "vhv": ["vlq", "vtg", "fxp"],
    "sbr": ["pjj", "vhk", "trz"],
    "nbt": ["tsz", "ttt"],
    "mlp": ["dch"],
    "fnc": ["lcj", "ncp", "dvd", "pkr"],
    "hbl": ["qlx"],
    "xpz": ["kqb"],
    "rkb": ["znx", "jnn"],
    "szp": ["rcp", "dvd"],
    "pqg": ["ggd", "bqs", "smd", "nlf"],
    "kkj": ["hdc"],
    "ggm": ["cxf", "kht"],
    "ljb": ["mjz", "gjx"],
    "cvl": ["xqp"],
    "mzt": ["hsc", "kcv"],
    "clt": ["qxx", "rvl", "ltm", "mpk"],
    "hgb": ["scc", "rgx", "shq", "zsk"],
    "fpc": ["bqf"],
    "qlh": ["cfc", "cdl", "zrf"],
    "xhh": ["ssf", "cns"],
    "mkh": ["pkj", "sxp", "qgn"],
    "zbr": ["fcm", "pfz", "bvx", "kml"],
    "ntf": ["qqq", "jpq", "phl"],
    "jzr": ["nkl", "ftg"],
    "qgj": ["bvl", "knv"],
    "vcg": ["xgm", "bkq", "pvq", "cks"],
    "mrh": ["kqb", "grk"],
    "rjz": ["tlf"],
    "cfg": ["bjf", "sxp", "lvv", "kmz"],
    "xpl": ["sxp"],
    "hcn": ["xxz", "nxt"],
    "gsr": ["ltx", "chc", "bcp", "ksx"],
    "dpg": ["rqq"],
    "gpn": ["czv", "czz"],
    "rmm": ["qdr", "bcj"],
    "dnj": ["zdc", "skf"],
    "zfq": ["rqr", "bzm", "xqp"],
    "vnf": ["gmk", "cbd"],
    "hcz": ["zhp", "pqx", "fvl"],
    "kpn": ["qvb"],
    "pmz": ["qks", "hpk"],
    "sgz": ["skh"],
    "gtt": ["vpn", "bbt", "spm", "kzg"],
    "xzk": ["fbr", "dfj"],
    "ldl": ["grp"],
    "hqn": ["zdg", "mcb", "qmp"],
    "chq": ["sht", "qkk", "vfz", "pqn"],
    "phg": ["jgm", "xzk", "trc", "rqx"],
    "jlj": ["psz", "rkq", "psc", "lqb"],
    "gjk": ["ncf", "mzh", "tzk"],
    "nrh": ["mqh"],
    "nmd": ["lkq"],
    "rxp": ["sgz", "hdq", "mqx"],
    "spz": ["dkg", "rkb"],
    "dfk": ["xtk", "ksx", "mcg"],
    "lbb": ["mlc"],
    "lrr": ["gxp", "ndv"],
    "ngp": ["lvg"],
    "dgn": ["cfc"],
    "qzc": ["dfj", "qjx", "fxm", "crq"],
    "qfg": ["cvm", "rkq", "qvr"],
    "tzm": ["jrm", "mzs"],
    "szz": ["kbp", "fnm"],
    "pnr": ["kzq", "xdb", "ntf", "xsv"],
    "xjg": ["bgl", "vtz", "mpk", "ncm"],
    "plh": ["rhj", "kkj"],
    "klm": ["tdt"],
    "lmb": ["kbs", "bqh", "slv", "bzl", "bbc", "rrb", "lhf"],
    "nlr": ["cmf", "cnj", "sfj", "xrs"],
    "xld": ["dlk", "kcv"],
    "pbn": ["pmf", "qbq"],
    "jhj": ["nfd", "jkh", "bzr"],
    "pgc": ["qrr", "mkb", "dhq", "ftm"],
    "gmk": ["bzm", "mlb", "xmj"],
    "ktq": ["mqs", "mhg", "cts"],
    "slt": ["llz", "gjb", "chc", "fdk"],
    "gjp": ["tkq", "lks"],
    "rbk": ["zzh", "lxr"],
    "fxk": ["dxq", "gff"],
    "dlz": ["qrp", "txz"],
    "ncz": ["vpf", "sgf", "knd", "gcv"],
    "cxn": ["skh"],
    "phk": ["lln", "pcl"],
    "fhg": ["gjk", "cbd", "nlr", "lnb"],
    "zhl": ["sgh", "fhl"],
    "gnp": ["tkx", "jkg", "tmq", "fzf"],
    "qjj": ["jql", "dps"],
    "dcl": ["tpf"],
    "sqh": ["pkj", "rqp", "qch", "rzp"],
    "fdh": ["sbr", "mxl", "vpt", "hpx"],
    "gdr": ["gjx", "ssm", "psk", "hkd", "tfg"],
    "lxl": ["fdc", "dlk", "gdh", "jrx"],
    "pnz": ["xsf", "hkr", "dfr"],
    "lsl": ["ljg"],
    "pbq": ["dgp", "ctq"],
    "lkr": ["bjf", "snz", "pzk"],
    "zmc": ["fdx", "vgh"],
    "bzk": ["zqr", "mvf", "sdr"],
    "pxn": ["nvb"],
    "fzz": ["dzt", "hhq", "lnx", "kqr", "ffp"],
    "ksx": ["nbq"],
    "gpl": ["cxl", "tfv", "lld"],
    "fcd": ["bdl"],
    "crd": ["hfx", "hsf", "fsp"],
    "svp": ["kqb"],
    "ddv": ["qfg", "srr", "ljm", "jdj"],
    "ncm": ["qdf", "kjl", "sjq"],
    "kbp": ["jfv", "kcg"],
    "fmq": ["hnp", "grd"],
    "hdq": ["lnx"],
    "ngn": ["jrl", "csk", "fkq"],
    "dch": ["fsd"],
    "ctf": ["mkq"],
    "tjj": ["qlt", "ckx", "rxh"],
    "cxb": ["cpg", "hpq"],
    "fpp": ["tmh", "qgp", "mfk", "xjn"],
    "dps": ["czr", "tln", "ksm", "nlq"],
    "jhq": ["zdt"],
    "qrq": ["xpz", "knh", "fcz", "llf"],
    "fsp": ["xmb", "dgx"],
    "xcf": ["fkq", "bkl", "nqz", "sgc"],
    "dsm": ["xpz", "vvf", "hvx", "jsx"],
    "brc": ["qfm", "dcj", "tkz", "dgp", "skb"],
    "tmf": ["vpz", "nlp"],
    "tsq": ["fdt", "dnt", "hjc"],
    "dxl": ["dhl", "bfn", "zqq"],
    "lbq": ["gqr", "lgc"],
    "xdh": ["kvx"],
    "bcd": ["glv"],
    "psc": ["xvc"],
    "zzx": ["qqr", "xhh", "spd"],
    "tmb": ["bpt", "ttk"],
    "hlz": ["qkt", "cfg", "lvp", "dpz", "nsz", "gpf"],
    "hrz": ["thv"],
    "ttl": ["rmm", "dnl", "bqs", "mzh"],
    "rlf": ["blj", "lfj", "mpt"],
    "chc": ["ntb", "grp"],
    "bzq": ["bkj", "xqk"],
    "trk": ["bnj", "hsc", "hpk", "stj"],
    "gmd": ["hfx", "nsx", "qxx"],
    "nnr": ["lgc", "tsj"],
    "qmr": ["hjd", "jmb"],
    "svf": ["vdv", "nrl", "vcd", "tqp", "ljd", "ghl"],
    "cqx": ["lkk", "jrm"],
    "rrs": ["vzr"],
    "grd": ["bcp"],
    "qbm": ["fbt", "krt"],
    "dbb": ["vpp", "llz", "nlq", "rcp"],
    "vns": ["rgf"],
    "bdq": ["psc", "qxt", "fxm"],
    "bfh": ["mbj", "lgg"],
    "qfx": ["hgz"],
    "vnq": ["jjq", "tzm", "vnf"],
    "lfd": ["ggm"],
    "lrp": ["krc", "xss", "bbq", "fjd", "lmz"],
    "nxt": ["drn", "rgz"],
    "xtk": ["nnv"],
    "rcp": ["sdf", "kcf"],
    "glm": ["ldl", "lsv"],
    "zlc": ["fpg"],
    "nvb": ["tdt"],
    "njs": ["dgp", "zhk", "spl", "zdg", "bcd", "hjz", "xrs"],
    "fnq": ["hdc"],
    "vjs": ["mjk"],
    "plt": ["nxd", "qjx"],
    "sdz": ["gxp", "jkf", "vbb", "glz"],
    "fnj": ["szz"],
    "pvf": ["qks", "cld"],
    "hsz": ["jrb"],
    "xct": ["spz", "ngb", "lhr", "kgz", "csz", "mkj"],
    "fqk": ["fmv", "rqm", "tfc", "glm"],
    "kkb": ["kpn", "khq", "szp", "fqr"],
    "bzf": ["hrv", "pbk", "jtf", "fhq"],
    "cdj": ["czv", "qdr", "kcv"],
    "msr": ["bcd"],
    "tbn": ["gnf", "xnx", "mjn"],
    "mfx": ["tps", "vjm", "phk", "vjd"],
    "vtc": ["gtd"],
    "dgm": ["gzv", "rxz", "chr", "vgg"],
    "vpf": ["cqz", "rqr"],
    "lrs": ["jbf", "dth", "jlr", "sdr", "spz", "lnb", "fpg"],
    "fbq": ["gqf"],
    "tln": ["kpn"],
    "txz": ["lhr"],
    "dtg": ["ltm", "rnx", "rqm", "dlv"],
    "nbh": ["fmt", "xgr", "drn", "sbm", "mqx"],
    "rnx": ["cbs", "mlx", "vgh", "ndr"],
    "mlm": ["vrk", "xmp", "kbl"],
    "jvt": ["kzq"],
    "llg": ["pdh", "frd", "ljd"],
    "ttb": ["jtm"],
    "sqf": ["jdf", "zxz", "jlr", "mmx"],
    "lpz": ["zpl", "qpp", "lxr", "ptl", "hpp"],
    "sxq": ["pcr", "pcm"],
    "slj": ["nzl", "mfr"],
    "qrv": ["tjj", "tkx", "bfn", "bzq", "mlz"],
    "rnr": ["svh"],
    "kfb": ["hcn", "fps", "jzk", "lbt"],
    "vtm": ["mkj", "dzp", "lfd", "ppp", "ddd"],
    "vxm": ["znx", "tlt", "qlt", "gdg"],
    "pmh": ["tkx"],
    "rsg": ["hrp", "zxz", "txz"],
    "bdj": ["hnq", "fhk"],
    "fjm": ["lrr", "hfl", "dpj", "zml"],
    "xmj": ["lxx"],
    "zfn": ["hbl", "flv", "gqt", "qbt"],
    "fzb": ["hqr", "fbr", "jvc"],
    "mcq": ["vrk", "xtb"],
    "vvc": ["plh", "fcd", "ffp", "fmv"],
    "gng": ["fkn", "jhj", "jkg"],
    "hvx": ["ffp", "vqm", "bjk", "fhl"],
    "snd": ["nfm", "zpl"],
    "qgp": ["rkq", "zbp", "jzk"],
    "zkg": ["rnr", "gpl", "kzm", "vbv"],
    "ltv": ["vlq", "zlq", "bzn"],
    "bsj": ["zzh", "fsd", "hfr", "bmd"],
    "qvq": ["khn", "mnc", "tfc", "rgz"],
    "khn": ["pqx", "gnr", "tpf"],
    "mth": ["xsx", "pvf", "zlm"],
    "mrz": ["rfx", "tcg", "qmh", "tfc"],
    "rqm": ["tfg", "plt"],
    "mqx": ["qpp"],
    "shr": ["kvx", "zjr", "sbg"],
    "jsd": ["vbm", "qnj", "vnr", "bjr"],
    "bvm": ["mjz", "nmm", "sjq", "tpt"],
    "bbt": ["grk"],
    "zjr": ["cbs"],
    "lvp": ["lbq", "msc", "cjz", "mmp"],
    "vft": ["nxt", "tfb"],
    "ghc": ["sdf", "lxr"],
    "nqc": ["bkv", "grp"],
    "fmh": ["bkf", "sxn", "xqs"],
    "hrh": ["psk", "blt", "qpx"],
    "cln": ["ktf", "vdk", "mfr", "sqs"],
    "txh": ["dbl"],
    "gsc": ["spt", "dpj", "xfv", "nrm"],
    "vtg": ["sgz", "xxc"],
    "gpf": ["pxt"],
    "rrb": ["ptp", "cbp"],
    "pxb": ["zpl", "qmh", "crd"],
    "xdm": ["fnj", "tdz", "ctf", "kzg"],
    "dnn": ["ngb", "lkk", "xlb"],
    "ggc": ["cck", "ddn", "ngp", "cms", "qnm", "jsr"],
    "mhg": ["msc"],
    "lff": ["vft", "prp", "kcf"],
    "fbk": ["trg", "dhh", "qzt"],
    "fcz": ["fmt", "pgt"],
    "mvf": ["nvd", "pfp", "lhr"],
    "cjz": ["pcl"],
    "psf": ["stj", "dkc", "dpg"],
    "zxs": ["dlv", "bqh"],
    "qgm": ["vbk", "grd", "jnv", "bdj", "ptp"],
    "rxz": ["jrc", "dkc", "zbv"],
    "mzj": ["dlf", "hxn", "kkb"],
    "rnh": ["jjr"],
    "kqt": ["xxz", "pnt", "szt", "xnx", "hxn"],
    "nlp": ["lcr"],
    "zxf": ["mhb"],
    "tmq": ["sgs", "pkp"],
    "cks": ["bzm"],
    "hkr": ["xdj", "hcm"],
    "flv": ["kqr", "rrb", "pkr", "mfq"],
    "jbl": ["qbq"],
    "srl": ["pvf"],
    "zvl": ["tkh", "nvb"],
    "zcb": ["thx", "ctq", "mfv"],
    "ljf": ["xxf", "bjf"],
    "gnf": ["vzn", "ltx", "hrh", "rhn"],
    "fjs": ["fzb", "bsb", "cvm"],
    "jfc": ["rgx"],
    "zxc": ["hjr", "knh", "mbm"],
    "flg": ["kmx", "qjh", "fnm"],
    "mmk": ["fcv", "srl", "xpn"],
    "dmx": ["fkx", "nfj", "mzf"],
    "hqh": ["lsl", "fsd"],
    "cck": ["gtd", "ghz"],
    "ccd": ["qfx", "pkj", "sqz"],
    "prz": ["fhq", "bzn", "xnx", "tkh"],
    "zxg": ["fdx", "lxv", "hkd", "mkq", "vfz", "qjj"],
    "dnq": ["vbv", "sfr"],
    "rxh": ["mgl"],
    "hdv": ["pdh", "bkl", "xjn"],
    "rlh": ["fnp", "jdf"],
    "xtb": ["szj"],
    "ngd": ["cnc", "hrk", "zvl"],
    "ncp": ["kcz", "tmh", "zvz"],
    "ccb": ["mkj", "smc", "shq", "zpd", "srl", "psx"],
    "jdx": ["clj", "mjk", "jtm"],
    "mcz": ["mbj", "ljn", "gjp", "bkf", "kkj", "nsf"],
    "tgc": ["tsq", "gvv", "zqh", "zpl"],
    "nsx": ["dch"],
    "fnx": ["pcr", "jkh", "tfd", "vqv"],
    "bcm": ["ttm", "bcd"],
    "qzt": ["rkb"],
    "dqn": ["nzl", "xlc"],
    "vbm": ["jkg", "xkh", "mzt"],
    "dcs": ["vzr", "rkh"],
    "dlk": ["jrd", "hsz"],
    "kmx": ["nsx", "ztm"],
    "hnl": ["nrh"],
    "vxp": ["smc", "gkv", "jrc"],
    "rxs": ["drn", "xmb", "tfv"],
    "czd": ["pmt", "dhl", "hgz"],
    "zbp": ["tvq", "srp"],
    "pqj": ["hjh", "svp", "vqg", "pxn"],
    "jsx": ["qgf", "xqs", "hnq"],
    "xdk": ["kqr", "csk"],
    "gcb": ["lbb", "zlk", "nrn"],
    "ddd": ["jxs"],
    "czc": ["bfh", "rbp"],
    "dvd": ["szz", "cct"],
    "tfd": ["mmk", "rrs"],
    "pfd": ["tnj", "xcp"],
    "lrx": ["txh", "qfx"],
    "thx": ["zbx", "jdf", "kfz"],
    "vpt": ["fpc", "ncm", "plt"],
    "bdf": ["cvl", "tlf", "xth", "gns"],
    "btq": ["jzk", "xqs"],
    "dkc": ["rxj", "nfh"],
    "ghz": ["dzv"],
    "rpt": ["dvk", "pmz", "zfj", "dnj"],
    "zpk": ["czc", "dgx", "ftr", "bqt"],
    "bft": ["zpl", "vpz", "xhh"],
    "fzc": ["rlh"],
    "nxz": ["jgp", "tlt", "ffd", "zxf"],
    "tbv": ["pzm", "txh"],
    "psx": ["fpg", "jbt"],
    "fdl": ["xjr", "lrr"],
    "ctv": ["mlx", "ztd", "sld"],
    "jbh": ["xlk", "mcv", "hjr"],
    "lnb": ["vjs"],
    "tct": ["bcj", "scc", "kbl"],
    "qlq": ["hfg"],
    "cpb": ["lbt", "qlb", "fjs", "bkl"],
    "jpk": ["gpq", "mzs", "qgj"],
    "tfb": ["gcz"],
    "kzm": ["ztm"],
    "pzb": ["ssq", "npj", "pmx", "lnb"],
    "ksz": ["fdt", "jfk", "slj", "hfg", "cnc"],
    "xfh": ["jpz"],
    "xtp": ["ctq", "cgd"],
    "jkb": ["hpq", "zdx", "mkl", "jdf"],
    "nth": ["vtg", "bkf", "xzp"],
    "tfc": ["hrn"],
    "nph": ["nbc", "ctq", "pmh", "zkq"],
    "bbq": ["tlf"],
    "vff": ["srp", "krq"],
    "ftg": ["nvv", "cmf"],
    "ntt": ["htc", "vdv", "bnk", "mbk"],
    "xjf": ["mbm", "mdg", "fbc"],
    "ljg": ["ksm", "fnk", "kfl", "brx"],
    "fkj": ["blj", "znj", "lhs", "bgj"],
    "sbg": ["jfg", "jtf"],
    "vvx": ["ndh", "sqf", "lrf", "fln"],
    "mpf": ["zsk", "lnp", "cjz"],
    "mrx": ["bqt", "hqh", "gzr", "fbc", "frh"],
    "bjk": ["vkg", "mqf"],
    "cvt": ["khq", "nsf", "vtg"],
    "jms": ["hcm"],
    "lnl": ["mqf", "spd", "mnc", "lzb"],
    "khc": ["ngp", "mfd"],
    "rzp": ["nzt", "ljf", "jpn"],
    "jrd": ["hpq"],
    "qlb": ["dbh"],
    "qrt": ["skh", "lcr"],
    "hmz": ["sqz", "zgd"],
    "ftc": ["rvf", "jjr", "hqn"],
    "ftm": ["gfb"],
    "vrg": ["dnf", "cqd", "kzq"],
    "bmb": ["pkc", "jpk", "fzc", "vjn"],
    "mpk": ["srh", "qqb", "vns", "dhk"],
    "gzh": ["djc", "qmr"],
    "ljk": ["fhq", "zjr"],
    "lxx": ["jbf"],
    "txd": ["xhg", "dqn", "nxs", "hpp"],
    "sgs": ["tnj"],
    "cbt": ["vpb", "mfv", "cvl", "ccl"],
    "czz": ["mfd", "dpj", "vjm"],
    "khz": ["gmk", "tcn", "pqg", "msr", "hgz", "tkx"],
    "qqg": ["vlb", "rbc", "fpk", "bfz"],
    "khq": ["fhk", "hnv"],
    "shq": ["phd"],
    "blg": ["gbx", "mnp"],
    "vjd": ["hnz", "vvj"],
    "fdk": ["nnv"],
    "nnn": ["dgx", "xxm", "fdg"],
    "rkd": ["msr", "vvj", "bjr", "kfm", "zxp", "sbl"],
    "sfv": ["vfz", "rbp"],
    "ckx": ["cms"],
    "hrm": ["bcp", "dnx"],
    "xxc": ["lnx", "hbk"],
    "dgb": ["pds"],
    "bsx": ["ddl", "xzh"],
    "nht": ["khq", "vdl", "xdb"],
    "qrc": ["dkt", "pds", "rkb"],
    "zlq": ["kbp", "zhp"],
    "ndb": ["zlc", "dkg", "sbl", "jdz"],
    "zms": ["zdt", "kht", "krc", "mph", "dbj"],
    "zjp": ["tqc", "mmx"],
    "zml": ["mdj", "znx"],
    "plj": ["vjz"],
    "lkf": ["dlz", "fbt", "pfd"],
    "xxz": ["qrr"],
    "rpm": ["vcn"],
    "ksd": ["nmn"],
    "smd": ["glv"],
    "zxx": ["pkp", "mlc", "xcp", "pht", "tlf"],
    "hjv": ["dlt", "xqk", "lnp"],
    "xsf": ["nrr"],
    "zrp": ["jql", "hcz", "rhf"],
    "mbm": ["xjn"],
    "cqz": ["dlg", "gtd"],
    "cdl": ["rfn"],
    "lqs": ["xlg", "qff", "jdz"],
    "zpr": ["phk", "bhj", "xfv", "tlj"],
    "cmn": ["dnf", "qvb", "bzn", "bnk", "vqk"],
    "hcr": ["mdb", "kcz", "fdx", "xhg"],
    "cpg": ["vkz"],
    "zrf": ["qsl", "rrf", "zhp", "kmx"],
    "ggd": ["cxf"],
    "kmz": ["rpm"],
    "jbt": ["lqs", "zjp", "lbz"],
    "lqh": ["dbh", "xnd", "xxz", "rqv", "qqp"],
    "dvk": ["fzf", "tkr"],
    "sgc": ["mkb", "jqf", "bjk"],
    "pkr": ["nxd", "nks"],
    "sxz": ["mrh", "gfb"],
    "lqm": ["kgz", "tbv"],
    "mfq": ["flg", "pdh"],
    "bql": ["gng", "lbq", "ptc"],
    "vjm": ["jkg", "xxf"],
    "ljd": ["fvz", "lkg", "kcf"],
    "kcc": ["mqh", "pmt", "tcq"],
    "dkg": ["djc", "xvb"],
    "ndh": ["fqn", "tcq"],
    "nfj": ["msc", "nkl"],
    "lcl": ["rgz", "gcz", "lbv"],
    "gzv": ["lkz"],
    "fmv": ["gff", "xlc"],
    "smc": ["gqf", "rjz"],
    "pkc": ["vgd"],
    "gsv": ["bvl", "zsv", "vtc"],
    "dcj": ["vlb", "gxp"],
    "jkl": ["zdc", "lkk", "xgm"],
    "vqt": ["nht", "pbn", "jnv"],
    "sgh": ["pll", "bbt", "jnv"],
    "lgt": ["jmb", "bkq", "zzg", "tbv"],
    "tkz": ["mjk", "mmv"],
    "dts": ["cqz", "gqr", "zpm", "tkr"],
    "qks": ["glv", "pcl"],
    "cxd": ["xgx", "psc", "gvr", "hpx"],
    "svh": ["ldl"],
    "cbr": ["ddd", "ckt", "cqj", "plb"],
    "bpf": ["tjf", "lvp", "blj", "ttm"],
    "rzq": ["nnm", "pgc", "zdh", "qcp", "qsk", "bft"],
    "qgf": ["jtl"],
    "jzg": ["mpt", "tlf", "jxs", "qzm"],
    "qsk": ["bnk", "dnt", "sxz"],
    "zdh": ["vff", "jtl", "ltv"],
    "qsr": ["bfx", "pxt", "fkx", "rlh"],
    "qlt": ["nzx", "jmb", "czv"],
    "sgg": ["hqh", "ltx"],
    "qjr": ["jdh", "hjd", "vpf", "srl", "gzz"],
    "pzv": ["szt"],
    "hsr": ["lrr", "rvf", "bfn"],
    "sht": ["fsp", "tds", "nks", "xqs"],
    "pkz": ["gcv", "pmz", "gsv", "fzc", "dcs"],
    "jvk": ["scc", "qzt", "pcm"],
    "rpl": ["dbn", "qcx", "tdq", "xfh"],
    "ccl": ["dgp", "hrp", "rxj"],
    "pjj": ["cxn", "xvc"],
    "slv": ["fll", "svp", "cxn"],
    "fqr": ["mdb", "lbv", "qgf"],
    "jjg": ["skt", "ngb", "bcm", "szj"],
    "vpz": ["xxc"],
    "zzd": ["gfb"],
    "zdx": ["mcq", "jxs", "mpb"],
    "gbd": ["csz", "cds"],
    "sqs": ["pfz", "fkd", "bgq", "bsb"],
    "vbk": ["lcj", "ztm"],
    "spl": ["bnj", "hfl"],
    "xqk": ["bbq"],
    "rkq": ["tmf"],
    "tbk": ["hcm", "kvx"],
    "tgl": ["hlt", "qrr", "hnv", "cbs"],
    "zhk": ["hqg", "lfd", "lqm"],
    "ptc": ["ppp", "mnp"],
    "gpj": ["lcg", "vqt", "bbt"],
    "gqc": ["dnj", "brm", "jfc", "vbb"],
    "kff": ["tzk", "hsz", "cck", "kcv"],
    "xmn": ["txz", "glv", "tsv", "nfh", "nbd"],
    "jsg": ["nrl", "tpp", "ckq", "tzd"],
    "xhm": ["tlk", "dlt", "zdc"],
    "pgh": ["tlj", "pcr", "pvh"],
    "pzc": ["hqg", "zrr", "vbb", "xlb"],
    "rmr": ["qlx", "jdj", "vpp"],
    "gvr": ["kbs", "qlq"],
    "zdt": ["lln"],
    "hqg": ["dlg", "bdf"],
    "gcj": ["hbk", "xsv", "dgn"],
    "dnf": ["cfc"],
    "qbt": ["ngd", "dcl", "zhl"],
    "mmq": ["jfv"],
    "hfk": ["nnn", "htc", "qqr"],
    "spv": ["jms", "vfz", "jvc", "zdm"],
    "tqp": ["lnl", "fqr", "hcq"],
    "lhr": ["gpq"],
    "glz": ["jjq", "nvd"],
    "jvd": ["kcz", "dzt", "fdx"],
    "nrc": ["vxp", "rqq", "pmt", "ccl", "qls"],
    "rfn": ["vpq", "qkk"],
    "ztd": ["hfg", "rnk"],
    "nxq": ["phv", "zbx", "nbt", "mlh"],
    "rmx": ["psz", "rrf", "cpn"],
    "zbx": ["cpg", "bjr"],
    "lbz": ["jrx", "ljt"],
    "zsh": ["pbk", "rzb", "tnf", "hbl"],
    "cnj": ["mjk", "rqr"],
    "ppz": ["lld", "kcg"],
    "rbh": ["cdl", "mbm", "pqx"],
    "dtc": ["vpq", "nxs", "drz", "nxd"],
    "kzx": ["xdk", "zqh", "lhf", "dhq"],
    "gkv": ["mlb", "bhs", "hdm"],
    "qjh": ["ktf", "tmh", "fxm"],
    "xjr": ["lkz", "zqq"],
    "gxp": ["rjz"],
    "jpp": ["thh", "cks"],
    "ssj": ["dzv", "nvd", "qzm", "vnf"],
    "xvb": ["jvb", "lhr"],
    "bkq": ["szj", "chr", "czz"],
    "fvp": ["nbt", "tzm", "fbq", "scb"],
    "lld": ["jtl", "cns"],
    "zbc": ["lgg", "brx", "vpz"],
    "lvv": ["xmp", "tvt"],
    "fll": ["xxc"],
    "rnk": ["bcp"],
    "cms": ["xmp"],
    "xsl": ["nzg", "jlp", "khq"],
    "xfm": ["sjc", "rvc", "dlf", "dqn"],
    "ssm": ["zzh", "tkh"],
    "rxx": ["pgt", "mcg", "tcx", "sgh", "xgx"],
    "hbq": ["tlj", "gpn", "npj", "ngp"],
    "vkr": ["mlx", "zhl", "rzq"],
    "dth": ["vcn", "mkh", "lnb"],
    "xlr": ["qtg", "dxg", "gnr", "vbv", "ltm"],
    "pgp": ["clj", "glz", "ttm", "pfd"],
    "slm": ["jrc"],
    "cvc": ["hbl", "tpf"],
    "nfd": ["ggm"],
    "vjn": ["qnj", "gtd", "ddd"],
    "ffd": ["lgm", "mkl", "xlb"],
    "lzb": ["knh"],
    "clf": ["pmv", "lbb", "vnr", "kxf", "qpz", "zdc", "ktq"],
    "clj": ["xmp"],
    "tjs": ["cdl", "zjr", "spm"],
    "qdr": ["lkr"],
    "nhn": ["ckq", "jvt", "rbd", "flh"],
    "prh": ["xnx", "pnr", "xtk", "fdg"],
    "mdj": ["ckx", "rxh", "gqf", "tzm"],
    "hjr": ["vpz"],
    "qxc": ["bgq", "kml", "mkb", "ndr"],
    "fpk": ["zjp", "ghz", "xxf"],
    "gqr": ["bbh"],
    "zrr": ["dlz", "sqz", "vzq"],
    "stt": ["pmf", "drn", "xzp"],
    "nzl": ["ghc", "xlc", "lbv"],
    "xlg": ["tsz"],
    "bhj": ["mzf", "pkc"],
    "fvz": ["vvf"],
    "bmr": ["lmz", "tcn", "xrn", "mph"],
    "zzg": ["hln", "gbd", "gzv"],
    "rhf": ["mkq", "mnx"],
    "xqg": ["ttb", "bvl", "mqz", "mcn"],
    "mkj": ["gxp"],
    "kbz": ["zmr", "fdf", "xcg", "pcm"],
    "kcp": ["jhz", "kxh", "gqr", "rjz"],
    "mcg": ["xtk"],
    "qpg": ["mpf", "jfc", "lxx"],
    "lbg": ["brg", "gsv", "xhm", "dkt", "pbx"],
    "sqz": ["ttb"],
    "xcg": ["ggj", "phd", "lkq"],
    "rtb": ["plb", "dpj", "vqv"],
    "khp": ["skp", "fgl", "nth"],
    "spq": ["qbc", "dnx", "cvc", "lcr"],
    "bfk": ["cqd", "mlp", "vtz", "cbp"],
    "bkl": ["dkl"],
    "lzl": ["qzt", "qkt", "xlg"],
    "nnt": ["plj", "ljb", "vdl"],
    "nnv": ["rdr"],
    "zhp": ["qdf"],
    "tzz": ["hnl", "mrr", "xpf", "tsj"],
    "pqx": ["svh", "qtg"],
    "vqg": ["vjz", "fgb"],
    "vdv": ["qcx", "tdt"],
    "mcb": ["rkb"],
    "nfm": ["csk", "rvc"],
    "fps": ["vzn", "fcz", "rnk"],
    "tkx": ["xpn"],
    "vqk": ["kcf", "crq"],
    "rbd": ["nnm", "gnr", "mnt", "mkb"],
    "xcp": ["lrf", "qzm"],
    "hsc": ["jhz", "pcm"],
    "rcz": ["xxs", "tnj", "sdr", "rvf"],
    "ttt": ["dhh", "vcn", "krc"],
    "nbc": ["jqb", "pzm"],
    "gmt": ["plt", "tln", "lpp", "gcz"],
    "vzn": ["ssf"],
    "rzb": ["ffp", "lrc", "xdk"],
    "mph": ["zkq", "vjs"],
    "fqf": ["fhq", "bqf", "tln", "sbg", "zng"],
    "mmp": ["rxh", "vnr", "nrh", "gqf"],
    "qqq": ["lks"],
    "krt": ["cds", "bbh"],
    "lsv": ["qjx", "plj", "pfz"],
    "mnc": ["vkg"],
    "xzm": ["kkj", "blt", "zdm", "hnv"],
    "ssq": ["sbl", "kxh"],
    "qkk": ["lcj", "cbs"],
    "bqt": ["vrg"],
    "rbc": ["fdf", "pdm", "pzk"],
    "kdx": ["hsf", "cbp", "tlz", "cjq"],
    "mns": ["snz", "bhs", "sqp", "zqr"],
    "bzr": ["lgm", "brm"],
    "rdb": ["zqm", "ljf", "trg"],
    "tfv": ["vkg"],
    "hpk": ["vkz"],
    "lhf": ["hdq", "fdg"],
    "vpn": ["hcm", "drz", "skh", "lxr"],
    "vxn": ["tmq", "hrp", "nvv", "mpb"],
    "jbf": ["ssn"],
    "msc": ["smd", "tkz"],
    "jgm": ["svp", "csk"],
    "ptp": ["nbb"],
    "cdv": ["kqb", "ksx", "rqv"],
    "gqt": ["hpp"],
    "qch": ["vrk"],
    "cqn": ["dpj", "sgs", "ghz", "dgb"],
    "tht": ["mhg", "jhz", "pbq", "nfd"],
    "nrn": ["cts", "jgp"],
    "gzr": ["srh", "sgh", "lzb", "fxk"],
    "xth": ["tvt", "ssq", "fpg"],
    "nks": ["xxm"],
    "mjd": ["kbq", "mnt"],
    "jhd": ["rvc", "fbr", "mbj"],
    "sdb": ["mcv", "gqt", "rmx", "ngn", "tbj"],
    "vkg": ["xdj"],
    "xgm": ["qmp", "ppp"],
    "nsc": ["gvg", "tvt", "pcr", "bkj"],
    "kbs": ["jbl", "jfg", "hlt"],
    "smm": ["bhj", "kcp", "mzq", "njv"],
    "bgj": ["ljt", "qgj", "dhl"],
    "ccq": ["dlv", "qxt"],
    "nnc": ["brg", "sqz", "dkt", "pmh"],
    "rxk": ["jvd", "lqr", "shr", "jql", "rrb", "llg", "mdb"],
    "jtm": ["prv"],
    "dlt": ["fdf", "mzs", "gdg"],
    "prv": ["zdg", "znx"],
    "dbx": ["zvl", "pfb", "fnk", "brf"],
    "hnz": ["lpq"],
    "ksj": ["ndr", "rnk", "ttk", "jqf"],
    "znj": ["krt", "xxf", "xzr"],
    "kjt": ["jqk", "nxs", "bkv", "xsz"],
    "mgl": ["dhh"],
    "glp": ["zfb", "lcj", "klm", "tln"],
    "xsv": ["dkl", "sld"],
    "xtq": ["rqv", "fvl", "fhq", "sxv"],
    "nxb": ["pnl", "lpq", "jrc", "fkx"],
    "ctd": ["dnn", "vdn", "gxp", "fzf", "jdx"],
    "tjp": ["rvn", "bln", "hrv", "rcp"],
    "bkf": ["cqd", "fnk"],
    "hdm": ["jbf"],
    "lzs": ["mbm"],
    "rtc": ["szt", "bmf", "bkf", "bln", "gfb", "sgg"],
    "gsl": ["xpm", "xdb", "bvx", "dnx"],
    "bvx": ["sdf", "zzd"],
    "sjk": ["mzt", "mvf", "kgz", "hnl"],
    "zng": ["vkx", "tfv"],
    "vvj": ["bjr", "qrp"],
    "rgr": ["tfb", "lpl", "nzl", "vzm"],
    "nbq": ["kml", "qqp", "phl"],
    "vpb": ["zjx", "lkv", "tfd", "rqp", "pdb"],
    "qdh": ["kjl", "cnc", "nsf", "cxl", "sxv"],
    "cts": ["qgb", "tvt", "prv"],
    "qjx": ["qsl"],
    "frd": ["nmm"],
    "lrc": ["jtl"],
    "gzl": ["fsg", "vpq", "dch"],
    "tcg": ["pzv", "jbh", "tbj"],
    "fbc": ["ktf"],
    "fkp": ["slm", "nzx", "jrd", "psx"],
    "tbc": ["cfc", "fll", "pxb", "zvz"],
    "jdz": ["cgd"],
    "bfz": ["zjp", "gbx"],
    "bmd": ["cvc", "fhq", "ngp"],
    "dxg": ["ccq", "fxp"],
    "lbv": ["cxn"],
    "xpm": ["jql", "tkh"],
    "ndr": ["fbc", "krq"],
    "ssr": ["qpg", "vsq", "nmn", "zml", "rmm"],
    "mzq": ["kht"],
    "hxq": ["ggr", "dnl", "jmc", "rqp", "msr"],
    "mnx": ["cdl", "vdl", "dnq"],
    "bzm": ["tps"],
    "tfr": ["jkg", "nvd", "fdl", "qls"],
    "ppp": ["gzv"],
    "bln": ["zkr"],
    "qsf": ["jfg", "nks", "gcj", "jrl", "hkr"],
    "bfx": ["pzj", "sbl", "zbv", "mpt"],
    "fkq": ["fhk", "fmt"],
    "ptl": ["llz", "fhk", "ldl", "hnp"],
    "pht": ["jdh", "gbx", "dzp"],
    "bbc": ["dfj", "ltm", "jkc", "psz"],
    "ntb": ["bkl"],
    "zth": ["mtb", "bql", "qnj", "pvf", "jkf"],
    "lxm": ["jqb", "zgd", "kxg"],
    "vpq": ["hfr"],
    "ksk": ["qqb", "dgx", "blh", "bmd"],
    "tqm": ["qlb", "pqn", "xtk", "hfr", "fsg"],
    "dbj": ["mgl", "sqz", "mzq", "xgm", "jfc"],
    "qlx": ["bqf"],
    "rqg": ["jrr", "hcm", "lbt"],
    "qqb": ["nvr", "vxz", "qdf"],
    "xmr": ["skp", "pkr", "nfm", "zjr"],
    "vkx": ["slj", "cdv", "ztd"],
    "xzh": ["blk", "lbb", "cmf"],
    "ckt": ["qgb", "jvk", "tjf", "lkf"],
    "mxl": ["nqt", "zlq", "zkr"],
    "dpn": ["hhq", "jhd", "tds", "pqx"],
    "jsr": ["grx", "nsd", "slm", "nrh"],
    "hln": ["qch", "npj"],
    "fcv": ["kcp", "zlc"],
    "mkl": ["jtm"],
    "zpd": ["fnx", "fcp", "dgb"],
    "rqq": ["pdm"],
    "skv": ["qqp", "chq", "gnf", "lmb"],
    "dbn": ["mfq", "tnf", "qrt"],
    "mdb": ["ghc"],
    "nhs": ["qmh", "bkv", "fdk", "qfd"],
    "ddn": ["dpg", "lkq"],
    "jlr": ["chr", "vkz"],
    "zfb": ["vqk", "nbb", "xvc", "sjq", "frd", "hrk"],
    "gfb": ["vdk"],
    "ttv": ["tzd", "nnm", "fhn", "xfm"],
    "tdq": ["tmb", "cnc", "vdl"],
    "mzh": ["lkz", "nmd"],
    "cxl": ["xlk", "jhd"],
    "tzs": ["nmn", "mkl", "zqr", "cgd"],
    "rln": ["qtg", "dcl", "psz", "prc"],
    "xqs": ["mnt", "bdl"],
    "pkq": ["ddf", "vkz", "pmx", "xpn"],
    "bfb": ["jzr", "xfv", "mzf", "gsc"],
    "qfd": ["fmv", "hjh", "kvg"],
    "nss": ["pxn", "jvf", "drz", "qlb", "mqf", "tpp"],
    "dpz": ["fln", "ndv"],
    "sgf": ["jhz", "cds"],
    "dzp": ["qch", "lfj", "vcn"],
    "lck": ["hrm", "jzz", "fmt"],
    "mlz": ["vjd", "blk"],
    "tnj": ["ksd"],
    "mbj": ["kpn"],
    "srr": ["pfz", "kld"],
    "fdc": ["cbd", "ptc", "vzq", "skf", "jxs"],
    "tll": ["hjc", "pqn"],
    "mtb": ["fbq", "dcs"],
    "lpl": ["zpl", "llf"],
    "pzj": ["jvb"],
    "lmf": ["stt", "fmf", "xfh", "zpk", "mjd"],
    "bxp": ["mmv", "hdm", "xxf"],
    "jlk": ["rmx", "kml", "pnz", "ljk"],
    "vcd": ["tpp", "qqp", "zxs"],
    "rhj": ["fmq", "xgr", "mjz", "zjr"],
    "mfk": ["pnt", "lks"],
    "lpk": ["hjd", "dkc", "lrx", "zml"],
    "nrl": ["tgt", "sxn"],
    "nqz": ["ljk", "sgg", "kzg", "lcg"],
    "bbh": ["qkt"],
    "dbh": ["fnk", "rqx"],
    "fhl": ["vhk", "lsv"],
    "ntg": ["qjh", "qxz", "zvz"],
    "rhn": ["srh", "rdr", "tnp", "bdq"],
    "tdz": ["kqm", "mqt", "vdk", "lck", "mrh"],
    "bdl": ["cpn", "mfr"],
    "pbx": ["zfj", "vnq", "qgn"],
    "xfv": ["plb"],
    "zph": ["rxs", "srp", "nzg", "tdq"],
    "lnh": ["rpm", "xqp"],
    "grl": ["szp", "grp", "zbp", "pnz"],
    "sdr": ["zlc", "jrx"],
    "tqh": ["xjr", "frn", "dpg", "dlv"],
    "cqj": ["xqc", "qzm", "nrm", "nsd"],
    "nbd": ["scc", "gpn", "vvj"],
    "lkk": ["cms"],
    "zdb": ["ctf", "tdm", "hdq"],
    "qfq": ["mqf", "jjf", "mkq", "fsd"],
    "rpx": ["pxn", "pgt", "qbt", "phl"],
    "rdr": ["lks"],
    "vkv": ["ptp", "zkg", "bgl", "xxm", "vzm"],
    "szh": ["gqt", "zxc", "xgx", "pnt"],
    "knd": ["lxx", "jnd"],
    "mdg": ["frh", "mnc", "drn", "vhv", "tkq"],
    "ttk": ["hpp"],
    "cbp": ["fnq", "qdj"],
    "hjp": ["zjr", "brf", "hlt", "rdr"],
    "fln": ["ssn", "rts"],
    "kdv": ["rqx", "rbh", "rbk", "sjc", "nth"],
    "jnd": ["pmh", "cds"],
    "fnm": ["nmm", "ksm"],
    "tsj": ["xrn", "ndv", "msr"],
    "vkb": ["mqh", "hpq", "tps", "lhs"],
    "bzl": ["pzv", "gzl", "kjl"],
    "blt": ["tmf", "tfb"],
    "ljm": ["jpj", "hcr", "xsz", "xjf"],
    "xzj": ["dkl", "vkr", "bll", "vtg", "ppz"],
    "mmv": ["fbt"],
    "xjj": ["jkh", "nzt", "pcr", "sgs"],
    "hnf": ["xtb", "qmr", "nnr", "gzh", "zcb"],
    "hdl": ["dkt", "xsx", "xrs", "fpg", "nmn"],
    "bvp": ["gtd", "grx", "rqq"],
    "gjb": ["zvz"],
    "jdh": ["xzr"],
    "phd": ["fqn", "zqq"],
    "llk": ["tpp", "qpp", "qvq", "bqf"],
    "jvb": ["jqb"],
    "ghm": ["pfp", "sdr", "cld", "nzt", "pcl"],
    "fkd": ["qsl", "qtg", "jms", "fbr"],
    "fdg": ["trz"],
    "gzd": ["fmq", "btq", "tnp", "hbl"],
    "vzr": ["mnp"],
    "qff": ["jnf", "nsd", "mzs"],
    "tdv": ["krq", "dbb", "lpl"],
    "tpp": ["mmq", "tdt", "tmb"],
    "bdr": ["qjh", "rqv", "nxt", "fvz"],
    "phc": ["lln", "xxs", "xzr"],
    "vfd": ["fgb", "dgn"],
    "qpx": ["hjh", "hnv", "dgx"],
    "bgl": ["nxs"],
    "btn": ["hsr", "lrf", "mcb", "ndf", "cxf"],
    "mjn": ["xnx", "kcg", "bgl"],
    "jqf": ["zvz"],
    "txx": ["mgl", "jsr", "ttn"],
    "crx": ["xnl", "fnq", "nsx"],
    "bgq": ["lzb"],
    "hrk": ["dxq", "pjj"],
    "fhn": ["fvl", "tkq", "hnp"],
    "pjr": ["rbh", "xsl", "ngn", "thv"],
    "pdb": ["bbq", "rgx"],
    "kfz": ["jkh", "tvt", "gpf", "phc"],
    "ddl": ["qfx", "dlz"],
    "vtr": ["jrx", "jvb", "gfc", "spl"],
    "ttn": ["qff", "mlb", "bfn", "qbm"],
    "kbk": ["vzr", "fdl", "xrn", "fxd"],
    "ffv": ["qzt", "tkr", "nnp", "hjv", "pdb", "jxj"],
    "nzg": ["llz", "lrc", "xdj"],
    "gzf": ["zqm", "txh", "hfl", "lfd"],
    "cjm": ["xlk", "qpx"],
    "qxm": ["pgt", "zzd", "fsg"],
    "csj": ["cck", "jdz", "lbz", "rkb"],
    "hcq": ["lsl", "fbr", "gjp"],
    "pmx": ["tqc"],
    "sdf": ["hlt"],
    "lbt": ["prc", "nlq", "lsl"],
    "qdj": ["cdl"],
    "vgh": ["trz"],
    "tjg": ["jjr", "msr", "sjk"],
    "ljt": ["fqn", "mvs"],
    "mqt": ["bzf", "ssf", "ttk"],
    "cdk": ["jtf", "spm", "jfk", "mrh", "nlp", "jpz"],
    "xmb": ["mjz", "mnt"],
    "sfj": ["dpz", "jkf", "pvh"],
    "bzn": ["vlq"],
    "bns": ["vnr", "kxh"],
    "xkh": ["gzv", "zpm"],
    "qgn": ["qdr", "mvs"],
    "njf": ["sjc", "hrz", "nqc", "kjl"],
    "vlb": ["ggj", "zjx"],
    "hjz": ["lqm", "cpg"],
    "pqn": ["cjq"],
    "hjh": ["hfr", "kcz"],
    "rhc": ["zms", "prk", "cxb", "krc", "ndv"],
    "jrl": ["gvr", "mtp", "szt", "gcz"],
    "ndv": ["lgm"],
    "bhs": ["ggj"],
    "sfr": ["qbq", "fdt", "qxt"],
    "rvl": ["cvt", "sdf", "hcr", "lff"],
    "tcn": ["gdh"],
    "hxn": ["psk", "sgz"],
    "mtg": ["bzk", "pmh", "ckm", "txx", "clj"],
    "rfg": ["tmq", "rtb", "nrh", "tqh"],
    "mcv": ["jjf", "fmh", "jfg"],
    "llf": ["hjc"],
    "qpz": ["fkx", "hjd", "dzv"],
    "skt": ["ttm", "gdg", "pdm"],
    "lcr": ["vpq", "hjh", "cct"],
    "scb": ["bcm", "tlj"],
    "xbm": ["szj", "cks", "ngb", "snz"],
    "tlz": ["hkr", "qqq", "jdj"],
    "jxv": ["gpn", "rgn", "jdf", "rjn"],
    "pkj": ["sgf"],
    "mcn": ["qrc", "nfd", "cqx", "dhl"],
    "vpp": ["skp"],
    "dhk": ["xdb"],
    "ckm": ["vnr", "tcq", "vjs"],
    "gxd": ["bgq", "dhk", "pbn", "nmm"],
    "vkl": ["xnl", "rbp", "jqf", "qsl"],
    "xlc": ["pmf", "rqx"],
    "gbx": ["ftc", "lpq", "nnr", "dnl"],
    "fkn": ["scb", "lpq", "gfc", "qgb", "nsz"],
    "jjf": ["brx", "czr"],
    "dkm": ["nbt", "bfz", "bbq", "kxh", "nzt", "cdj"],
    "drr": ["xtp", "nfd", "zsk", "mtb", "knv"],
    "gzb": ["dcs", "mlh", "zqm", "kmz", "cbd"],
    "fjd": ["ftg", "hgz", "glv", "jqb"],
    "rfx": ["qdj", "fxp", "mqf"],
    "cbz": ["lqs", "hfl", "pds", "mhg", "hmz"],
    "nvp": ["czr", "tfb", "kfl", "hkd", "crx"],
    "dzt": ["cqd", "kqb"],
    "lcg": ["kpn", "mnt"],
    "vjz": ["bqf"],
    "hbs": ["dsp", "ccd", "qgj", "gfc"],
    "hkd": ["vqk"],
    "sjc": ["sxn"],
    "tvq": ["brx", "xvc"],
    "jpd": ["kzg", "qxt", "kqb", "ztd"],
    "xhj": ["fnj", "lgg", "vgh"],
    "bqs": ["qmp"],
    "htc": ["gvv", "vhk", "fgb"],
    "ccp": ["sbm", "fgb", "tvq"],
    "prk": ["mqh", "kcc", "fnp"],
    "xsz": ["nks", "jnv"],
    "fxj": ["blh", "gmd", "fnq", "cct"],
    "nxd": ["hnp", "zkr"],
    "pnl": ["jnn"],
    "hnq": ["nvr"],
    "pvh": ["vgd", "vdn", "cms"],
    "njv": ["bbh"],
    "pfp": ["lfj", "xjr"],
    "fcm": ["jpq", "jpz"],
    "mrr": ["bvp", "tct", "kmn"],
    "gnq": ["lbt", "bcp", "hfx", "dfr", "rdr"],
    "fgh": ["hfk", "nqc", "pnt", "hlt"],
    "dhq": ["mbj", "kvx"],
    "kqr": ["vvf"],
    "sjz": ["vzn", "hrn", "tll", "jtl"],
    "qrr": ["xlk"],
    "ssc": ["nnm", "tlz", "cvc", "vpq"],
    "zss": ["xqp", "jnf", "xmj", "fbt", "zjx"],
    "qcp": ["tdm", "xzp", "vpp"],
    "vhd": ["bkj", "skt", "mvs", "tjf"],
    "qbc": ["nrr", "rqg", "nvb", "qlx", "rnx"],
    "jxj": ["tcn", "rdq", "qbm"],
    "tsv": ["mlm"],
    "cvm": ["tbk", "rbk"],
    "lrf": ["bnj"],
    "hpx": ["qlq", "xhj", "lzs", "dfj"],
    "fhq": ["csk"],
    "tzd": ["qmh", "vpz", "mmq"],
    "vgg": ["zsk", "kcc", "nfh", "mtg"],
    "spd": ["hfg", "qxt"],
    "thh": ["gzp", "xxs", "vbm"],
    "xgl": ["mlc", "jhq", "fbq", "nkl"],
    "kbq": ["cct", "qxz", "fvz"],
    "ljn": ["zlq", "crx", "lqb", "frd"],
    "rqr": ["prv", "lnh"],
    "dsp": ["ggd", "bjf"],
    "cld": ["pds"],
    "hdg": ["mlp", "gvv", "cns", "xdj"],
    "ndf": ["bzr", "cxb"],
    "tlj": ["dzv"],
    "xrs": ["xjr"],
    "gff": ["fvl"],
    "mmx": ["pmv"],
    "jgp": ["xpl", "crr", "tbv", "lgc"],
    "dfj": ["rgf"],
    "ghl": ["vdk", "fdg", "mqf"],
    "fmj": ["rbp", "dnt", "kqm", "ftm"],
    "pld": ["mqh", "mvs"],
    "lkv": ["bns", "kcv"],
    "bfj": ["pvq", "nrn", "lrx", "xpf"],
    "qqh": ["lrc", "chc", "tpf", "sjq"],
    "xtv": ["kfl", "sbm", "fvl", "xnl"],
    "nnp": ["jdh", "mlh", "zxf"],
    "fzf": ["bcj", "sbl"],
    "fbp": ["fxp", "qjj", "nnv", "qvb"],
    "prc": ["ssf", "jdj"],
    "lsz": ["tcg", "gpj", "sjq", "nmm"],
    "nlf": ["gmk", "gpq", "mvf"],
    "qfm": ["bbq", "brm"],
    "flh": ["sxn", "ktf"],
    "xnd": ["dgn", "bfh", "bqt"],
    "kqm": ["vpt", "lld", "xxz"],
    "knr": ["pzg", "mmv", "zsv", "mmk", "xlg"],
    "pll": ["gjb", "kbp"],
    "vqm": ["rln", "snd", "cfj"],
    "jjp": ["lhs", "rkh", "bql", "mqs"],
    "jkc": ["knh", "mqx", "plt", "xsf"],
    "cgz": ["lzs", "fxk", "lnx", "zbc"],
    "mqz": ["vqv", "lmz"],
    "hhj": ["plh", "ntg", "pqn", "zxs"],
    "gns": ["cjz", "gpq"],
    "vxz": ["mlx"],
    "fqs": ["dxg", "skp"],
    "txf": ["ggj", "ggr", "lkv", "jpp"],
    "ttm": ["mzq"],
    "dpd": ["cbp", "ppz", "hhj", "xdh"],
    "fmt": ["qqq", "fdt"],
    "tnp": ["nnt", "sfv"],
    "tmm": ["lgc", "vvj", "jdh", "pzj", "mlz"],
    "fnp": ["xpf", "pmv"],
    "stj": ["dbl"],
    "fpj": ["cqx", "smc", "mcq", "dts"],
    "cxf": ["zdg", "jrb"],
    "pnt": ["lcl"],
    "kdh": ["ksm", "ntb", "zmq", "tbj", "mjn"],
    "zqm": ["blk"],
    "mfv": ["rlf", "dbl", "vtc"],
    "jck": ["hsz", "kfz", "kht", "gcv"],
    "thv": ["fcd"],
    "crr": ["qmp", "gns"],
    "jdn": ["xlc", "dhk", "ckq", "ctf", "xtk"],
    "jxr": ["mzs", "jdf", "ssn", "skf"],
    "zfj": ["xfv"],
    "xgx": ["gjb", "qxz", "qdf"],
    "sld": ["ghc"],
    "qgc": ["xmn", "nrn", "bzq", "kfm", "cnj", "pvf", "xmp"],
    "dfc": ["dgx", "lgg", "pfz", "ccp", "xxm"],
    "vkf": ["crr", "jvb", "nfh", "qfm", "cts"],
    "xpf": ["xpn", "mnp"],
    "lts": ["spv", "lqb", "klm", "kld", "qxm"],
    "vvf": ["vxc"],
    "nsf": ["vzm"],
    "pvq": ["qgb", "sxp", "dgb"],
    "kks": ["hbq", "jhq", "xld", "pvf"],
    "prp": ["vtz", "flh", "hbk"],
    "ljz": ["ssn", "tsz", "mlc", "bjf"],
    "gnr": ["vls"],
    "dnx": ["crq"],
    "dlg": ["rsr", "cds"],
    "nlq": ["skp", "vlq", "sbm"],
    "pxt": ["gqr", "xkh"],
    "hsf": ["hcm", "bdl"],
    "kbl": ["zqm", "gfc", "sxq"],
    "qxx": ["tbj", "fcd", "jzz"],
    "jvc": ["lsl", "vzm"],
    "lqr": ["xrr", "hfg", "xhg"],
    "lmv": ["mjn", "qfd", "bsj", "bvm"],
    "bvl": ["bnj"],
    "kld": ["trz", "hdc"],
    "vsq": ["vgd", "phk", "nzx"],
    "krz": ["bzm", "ljz", "gzz"],
    "sdk": ["djc", "cvl", "bcm", "qrp", "dhh", "gcv"],
    "lvg": ["tps", "nrm"],
    "tdm": ["ftm", "jzz", "vxz"],
    "nnx": ["hmz", "hjz", "pgh", "lfj"],
    "sqp": ["jhq", "bkj", "tqh"],
    "tgt": ["mfr", "bsb", "vxc", "jpq"],
    "vhk": ["vkg"],
    "zvd": ["gzv", "mlh", "bxp", "blg"],
    "bsq": ["fqk", "cjq", "bcp", "krq"],
    "zmq": ["fmh", "nrr", "zdb"],
    "htf": ["mlb", "mcb", "xlb", "pkc"],
    "jhg": ["ksx", "nqt", "cjm", "fqs", "snd", "mzj", "zmc"],
    "xcs": ["tbn", "vjz", "cbs", "dcl"],
    "ssl": ["sbl", "jrc", "ljt"],
    "hnb": ["ckq", "qqr", "klm", "fcm"],
    "sxv": ["hhq", "dxq"],
    "trc": ["sfv", "jms", "xdh"],
    "nvk": ["tsv", "nzt", "xtp", "tcq"],
    "nkt": ["njv", "gqf", "ckt", "lgm", "jrb"],
    "ztt": ["kjt", "cns", "zkg", "xfh"],
    "xrr": ["phl", "vxz"],
    "rjb": ["njv", "xtb", "qmr", "mvf"],
    "fhk": ["zvz"],
    "bll": ["tkq", "dnf", "mlp"],
    "ftr": ["ssm", "vdk", "vqg"],
    "nqt": ["tbk"],
    "zmd": ["mjk", "rgx", "jhq", "ffv"],
    "frh": ["nkh", "xhg"],
    "fbt": ["qzm"],
    "qcv": ["gcj", "ctv", "cpn", "lbv", "ccq", "sld"],
    "zmr": ["lkq", "lln", "stj"],
    "zbv": ["pzk"],
    "skb": ["sxp", "zxz", "mvs"],
    "mtp": ["gfb", "gqt", "stt"],
    "qqr": ["tjs", "kzm"],
    "mpb": ["vrk", "pkc"],
    "dzz": ["gqc", "qkt", "tjf", "jrm"],
    "bcj": ["brg"],
    "zjx": ["zgd"],
    "qxz": ["hjc", "vfd"],
    "tkr": ["gpf"],
    "fsg": ["gfb", "qgf"],
    "mbk": ["dvd", "pnz", "brf"],
    "mqk": ["mqt", "tzd", "mfk", "vfd"],
    "hrn": ["qbq", "thv"],
    "jnf": ["lmz"],
    "lkg": ["tds", "xlk", "bqh"],
    "zst": ["dkg", "bsx", "nfj", "gbx", "tzk"],
    "fcp": ["jjr"],
    "ggr": ["bhs", "jrm", "gkv", "zpm", "fcp"],
    "grx": ["qfx", "xzr"],
    "crf": ["bsb", "cxl", "dhk", "rxs"],
    "qvr": ["jjf", "jgm"],
    "cfj": ["qsl", "vdk", "glm"],
    "tfg": ["qzc", "fsd"],
    "xrb": ["smd", "jpp", "vrk", "rrs", "mth"],
    "bpg": ["cmf", "pkc", "plb", "ckx"],
    "zqh": ["rfn", "nlp"],
    "htt": ["vns", "tnf", "zng", "sxz", "tmh"],
    "czr": ["gff"],
    "dhh": ["jmb"],
    "hrv": ["pqx", "xpm"],
    "jlp": ["fnj", "hfx", "plt"],
    "dbl": ["xtb"],
    "rxj": ["qnj", "pdm", "vkz"],
    "qls": ["cgd", "ghz", "pnl"],
    "pfb": ["llf", "svh", "jzz"],
    "mpz": ["czc", "jbl", "lzs", "dnt"],
    "dfr": ["mqx", "vls"],
    "blv": ["qrc", "mmk"],
    "czl": ["zrp", "jtf", "xrr", "txd"],
    "jpj": ["bzl", "mcg", "hdc", "nqt"],
    "dlf": ["khp", "kbp"],
    "dgx": ["jvt"],
    "bpt": ["plj"],
    "zlm": ["tsz", "ccl", "nvv", "rnh"],
    "kbv": ["vdk", "klm", "hcn", "tpf"],
    "xlk": ["rgz"],
    "fgl": ["zzd", "flh", "vff"],
    "tlt": ["bqs", "ksd"],
    "zxp": ["cgd", "tnj", "rqr"],
    "rsr": ["zsk", "lkz", "hnz", "xxs"],
    "gvg": ["lvv", "lnh", "npj", "gdg"],
    "mfd": ["tqc"],
    "bqd": ["nsc", "rdb", "xpl", "zdx"],
    "jhf": ["tjg", "krt", "rnh", "scc", "hpq"],
    "qzz": ["xmj", "qnm", "ssj", "fxd", "mnp"],
    "nkl": ["lvv", "nrm", "fcp"],
    "fdf": ["blj"],
    "bmf": ["xzk", "mmq", "xgr"],
    "tbp": ["srh", "tds", "qcx", "hrz", "jbl", "kzm"],
    "rts": ["zkq", "djc", "bhj"],
    "rdq": ["phc", "mhb", "dlz"],
    "rrf": ["mnt"],
    "zqr": ["jrc", "dnl"],
    "jzk": ["tbj"],
    "jrr": ["tll", "bpt", "kcg"],
    "xnz": ["fdl", "pmt", "nvv", "rsg"],
    "srt": ["pld", "lhs", "jrb", "zxz"],
    "lnp": ["sgf"],
    "gzz": ["rvf", "mfd", "dlz"],
    "jvf": ["qrt", "hdv", "kzq"],
    "kfm": ["tzp", "hdm"],
    "lqq": ["gcb", "vtc", "csz", "jrd"],
    "tbx": ["lqb", "xsf", "sjz", "nrr", "fll", "pdh", "qpp"],
    "kmn": ["phk", "qzm", "gzp", "brm"],
    "xqc": ["psf", "pkp"],
    "bnk": ["hdq"],
    "kvg": ["bkv", "nbb", "hdq"],
    "hqr": ["pzv", "hnq", "xpz"],
    "pzg": ["bkj", "pkp"],
    "rvc": ["jvt", "tnf"],
    "xnl": ["srp"],
    "shl": ["ktq", "ddn", "xld", "pzj", "nsd", "tqh"],
    "rdd": ["rgn", "sxq", "fdf", "brg"],
    "jpn": ["jnd", "qrp", "bns"],
    "ncf": ["jnf", "szj", "nmd"],
    "spt": ["pzg", "knd", "hpk"],
    "tpf": ["qvb"],
    "vzq": ["nrh", "pcm"],
    "fxd": ["rdd", "dts"],
    "dhp": ["gmt", "zzh", "xdh", "bjk", "kfl"],
    "zkr": ["fpc"],
    "zqq": ["czv", "tkx"],
    "nsz": ["xvb", "ngp"],
    "fmf": ["zrf", "ccp", "vff", "zdm", "hqr"],
    "knv": ["rrs"],
    "kxg": ["fnx", "blv", "rmm"],
    "blh": ["ljb", "rnr", "hrz"],
    "zmx": ["fnk", "pbk", "bln", "hrm"],
    "qqp": ["ztm"],
    "qfj": ["rmr", "hjr", "jqk", "ntb", "hbk"],
    "fvl": ["xjn"],
    "gjx": ["qtg", "rgf"],
    "xdb": ["gfb"],
    "tnd": ["pnl", "fcv", "gsv", "xqk"],
    "rjn": ["kmz", "lvg", "pbq", "rgn"],
    "rkh": ["xqk", "bbq"],
    "fkv": ["qlh", "dxq", "fjs", "mjd"],
    "jqk": ["pmf", "zvz"],
    "dkl": ["crq"],
    "nvr": ["nmm"],
    "rgn": ["vdn"],
    "vzm": ["qlq"],
    "ddf": ["fkx", "ddl", "hln", "fbk"],
    "xss": ["czd", "lxm", "blg"],
    "phv": ["blk", "rnh", "knv"],
    "gdh": ["ssl", "tqc"],
    "pxs": ["dfk", "zzx", "xxz", "kkj", "zdm"],
    "jfk": ["vfd", "vbk"],
    "snf": ["fmf", "sjc", "nsf", "lck"],
    "nsv": ["jnf", "mhb", "ttb", "vbb"],
    "xsx": ["jhq", "jdx", "dcj"],
    "tzp": ["nrm", "lnp", "zkq"],
    "mpt": ["hnz"],
    "nkh": ["dnq", "brf", "xgr"],
    "tcx": ["rxp", "fpc", "pll"],
    "jkf": ["lkr"],
    "jfg": ["grd"],
    "pzm": ["zgd"],
    "kpc": ["zfj", "rlf", "dvk", "shq", "bnj", "krz", "vjs", "fzc", "hnl"],
    "rvn": ["gvv", "fnm", "vft"],
    "jjq": ["snz", "pld", "gbd"],
    "tpt": ["hhq", "gfb", "kvx"],
    "cbd": ["cvl", "mqz"],
    "bqh": ["skh"],
    "ppn": ["pmv", "kgz", "phc"],
    "vls": ["fdk", "qtg"],
    "gzp": ["fqn", "vgd"],
    "vqv": ["mhb"],
    "kxf": ["cbz", "ckm", "zbv"],
    "lxc": ["nlr", "lzl", "nxz", "trg"],
    "ltx": ["jfv"],
    "tdr": ["mnx", "bpt", "nbb", "vbv"],
    "lxv": ["dch", "rrf", "vvf"],
    "kvr": ["pld", "ftg", "chr", "ppn"],
    "dhf": ["dvd", "vns", "drz", "bdj"],
    "rnd": ["tfg", "btq", "tdv", "vtz"],
    "ldd": ["rgf", "rhf", "srr", "vxc", "cjm"],
    "xrn": ["slm"],
    "tbh": ["flh", "fxm", "spm", "dkl"],
    "dhl": ["qmp"],
    "cvh": ["dmx", "jzr", "cld", "pmx", "ndf"],
    "zlk": ["xpl", "vdn", "jnn", "zdt"],
    "tqr": ["grd", "trg", "mkl", "zfq"],
    "zpm": ["pzk"],
    "hrp": ["nmd"],
    "frn": ["jnn", "zxf", "ksd"],
    "dkx": ["rnr", "fqr", "qvr", "nvr", "mfk"],
    "lpp": ["vxc", "qdj", "cpn", "kpn"],
    "jmc": ["tzk", "jjr", "rpm"],
    "dfh": ["jkl", "gzh", "zsv", "zbv"],
    "mqs": ["pnl", "pkp", "ccl"],
    "zpl": ["cjq"],
    "kzg": ["psk", "jgm"],
}

G = nx.Graph(graph)

view = nx.draw(
    G,
    pos=None,
    ax=None,
    with_labels=True,
    font_size=20,
    node_size=2000,
    node_color="lightgreen",
)

import matplotlib.pyplot as plt

plt.show()
